version: '3.2'

networks:
  data_network:
    external: true
  be_network:
    external: true

secrets:
  cukereports.mongodbuser:
    external: true
  cukereports.mongodbpass:
    external: true
  cukereports.mongodbserver:
    external: true

services:
  ${project.artifactId}:
    image: ${hub}/${org.prefix}/${project.artifactId}${service.suffix}:${project.version}
    hostname: cukereports
    #volumes:
    #  - /opt/cronjob/docker:/opt/hostcrons
    networks:
      data_network:
        aliases:
          - cukereports
      be_network:
        aliases:
          - cukereports
    ports: 
      - "38081:8080"
    #environment:
    #  - ENV_SECRETS_DEBUG=1
    secrets:
      - cukereports.mongodbuser
      - cukereports.mongodbpass
      - cukereports.mongodbserver
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.datacenter == lisboa
    #  resources:
    #    limits:
    #      cpus: '0.10'
    #      memory: 128M
    #    reservations:
    #      cpus: '0.10'
    #      memory: 64M
    